name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master         # Push events on master branch
    # Sequence of patterns matched against refs/tags
    tags:
      - v.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Run Buildx
      run: docker buildx build --build-arg DEBIANTAG=buster-slim --platform linux/amd64,linux/arm/v7,linux/arm64 --output "type=local,dest=output" -t entrypoint .
    - name: Generate Changelog
      run: echo "# Changelog" > ${{ github.workflow }}-CHANGELOG.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          output/linux_arm_v7/entrypoint
          output/linux_arm64/entrypoint
          output/linux_amd64/entrypoint
        body_path: ${{ github.workflow }}-CHANGELOG.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/heads/master')
      with:
        files: |
          output/linux_arm_v7/entrypoint
          output/linux_arm64/entrypoint
          output/linux_amd64/entrypoint
        body_path: ${{ github.workflow }}-CHANGELOG.txt
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
