name: CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master         # Push events on master branch
      - 'releases/**'  # Push events to branches matching refs/heads/releases/10
    # Sequence of patterns matched against refs/tags
    tags:
      - v.*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
      with:
        version: latest
    - name: Run Buildx
      run: pwd && ls -la && docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 --output "type=image,push=false" .
